# file: .swiftlint.yml
# SwiftLint configuration for Google Swift style guide

# Directories to include/exclude
included:
  - Sources
  - Tests
excluded:
  - Carthage
  - Pods
  - .build

# Rules configuration
rules:
  # Enabled rules
  - trailing_whitespace
  - leading_whitespace
  - vertical_whitespace
  - line_length
  - file_length
  - type_name
  - variable_name
  - function_name
  - identifier_name
  - cyclomatic_complexity
  - function_body_length
  - type_body_length
  - function_parameter_count
  - nesting
  - redundant_discardable_let
  - redundant_optional_initialization
  - redundant_nil_coalescing
  - redundant_type_annotation
  - redundant_void_return
  - syntactic_sugar
  - control_statement
  - force_cast
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - weak_delegate
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - vertical_parameter_alignment
  - opening_brace
  - closing_brace
  - colon
  - comma
  - operator_whitespace
  - return_arrow_whitespace
  - statement_position
  - switch_case_alignment
  - todo
  - mark

# Disabled rules
disabled_rules:
  - trailing_comma
  - multiple_closures_with_trailing_closure

# Rule customization
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 200
  error: 350

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 15

nesting:
  type_level:
    warning: 3
    error: 5
  statement_level:
    warning: 4
    error: 6

type_name:
  min_length: 3
  max_length: 40
  excluded:
    - iPhone
    - ID
    - URL
    - UUID

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - to
    - of
    - at
    - in
    - on
    - up
    - go

variable_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - to
    - of
    - at
    - in
    - on
    - up
    - go

# Custom rules
custom_rules:
  # Google style: prefer explicit self when needed
  explicit_self:
    name: "Explicit Self"
    regex: 'self\.'
    capture_group: 0
    message: "Use self only when needed"
    severity: warning

  # Google style: no empty lines at start of blocks
  no_empty_line_after_opening_brace:
    name: "No Empty Line After Opening Brace"
    regex: '\{\n\s*\n'
    message: "Don't add empty line after opening brace"
    severity: warning

  # Google style: no empty lines before closing brace
  no_empty_line_before_closing_brace:
    name: "No Empty Line Before Closing Brace"
    regex: '\n\s*\n\s*\}'
    message: "Don't add empty line before closing brace"
    severity: warning

# Reporter type
reporter: "xcode"
